#!/bin/bash
# wes-score GPU 워커 — 컨테이너 환경 파일 생성(#87). systemd 유닛(wes-score-gpu.service)의 run 스크립트가 매 기동마다 부른다.
#
# 비밀·설정을 AMI 에 굽지 않는다(인프라 계획 결정 J). 인스턴스 역할이 읽을 수 있는 SSM 파라미터 **세 개**만 읽는다:
#   /wes/prod/photoselect.db.password   SecureString  → DB_PASSWORD
#   /wes/prod/spring.datasource.url     String        → DB_HOST · DB_PORT · DB_NAME  (jdbc:postgresql://host:port/db?…)
#   /wes/prod/app.storage.bucket        String        → S3_BUCKET
# 결과는 tmpfs(/run) 에 0600 으로 — 디스크에 남지 않고, 유닛이 끝나면 지운다(ExecStopPost).
set -euo pipefail

REGION="${AWS_REGION:-ap-northeast-2}"
PREFIX="${WES_SSM_PREFIX:-/wes/prod}"
OUT="${WES_SCORE_ENV_FILE:-/run/wes-score.env}"

param() { aws ssm get-parameter --region "$REGION" --name "$PREFIX/$1" --with-decryption --query Parameter.Value --output text; }

JDBC_URL=$(param spring.datasource.url)
DB_PASSWORD=$(param photoselect.db.password)
S3_BUCKET=$(param app.storage.bucket)

# jdbc:postgresql://HOST:PORT/DB?sslmode=require → 세 조각. 포트가 없으면 5432.
rest="${JDBC_URL#jdbc:postgresql://}"
hostport="${rest%%/*}"
dbq="${rest#*/}"
DB_NAME="${dbq%%\?*}"
DB_HOST="${hostport%%:*}"
DB_PORT="${hostport##*:}"; [ "$DB_PORT" = "$hostport" ] && DB_PORT=5432
[ -n "$DB_HOST" ] && [ -n "$DB_NAME" ] || { echo "spring.datasource.url 을 못 읽었다: $JDBC_URL" >&2; exit 1; }

ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
ECR_REGISTRY="$ACCOUNT.dkr.ecr.$REGION.amazonaws.com"

umask 077
cat > "$OUT.tmp" <<ENV
# generated by wes-score-env.sh $(date -u +%FT%TZ) — do not edit
AWS_DEFAULT_REGION=$REGION
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USER=photoselect
DB_PASSWORD=$DB_PASSWORD
DB_SSLMODE=verify-full
DB_SSLROOTCERT=/opt/rds-ca/global-bundle.pem
S3_BUCKET=$S3_BUCKET
# 워커(#75·#81): 32장 배치, 3초 폴링, 유휴 30초면 자기 정지(다중 사용자 운영이면 600). 연속 실패 5회면 exit 1.
WORKER_BATCH=32
WORKER_POLL_SECONDS=3
WORKER_IDLE_STOP_SECONDS=${WORKER_IDLE_STOP_SECONDS:-30}
WORKER_MAX_CONSECUTIVE_FAILURES=5
# GPU 손잡이 — SageMaker ml.g6.xlarge 검증값(#79·#81). CPU Lambda 는 이 값을 쓰지 않는다.
SCORE_DEVICE=cuda
SCORE_FP16=1
CLIP_BATCH=32
ARNIQA_BATCH=8
SCORE_DECODE_WORKERS=4
SCORE_DOWNLOAD_WORKERS=16
SCORE_WORK=/tmp/score
# run 스크립트 전용(컨테이너에도 들어가지만 무해)
ECR_REGISTRY=$ECR_REGISTRY
ECR_IMAGE=$ECR_REGISTRY/wes-score:gpu
ENV
mv -f "$OUT.tmp" "$OUT"
echo "wes-score env: $OUT (db=$DB_HOST:$DB_PORT/$DB_NAME bucket=$S3_BUCKET image=$ECR_REGISTRY/wes-score:gpu)"
